### ISSUE TITLE
Mention Ruby... somewhere?

### ISSUE THREAD

**Issue by xiongchiamiov** [joshbuddy/optitron#1]
My suggestion is to change your description to "Sensible, minimal simple options parsing and dispatching for Ruby. Build a CLI with no fuss.".

Sure, once you get to the project page, the code looks like Ruby, and there's a gemspec and whatnot, but you never actually mention what language this is for.  It's even more important when looking at something like [the Explore GitHub page](http://github.com/explore) (where I found it) or [your userpage](http://github.com/joshbuddy) (although that does say that the primary implementation language is Ruby).

**Comment by joshbuddy** [comment]
I stuck a couple of refs in there.. how does that look?

**Comment by xiongchiamiov** [comment]
Wonderful.
