### ISSUE TITLE
All instance methods are interpreted as commands

### ISSUE THREAD

**Issue by knoopx** [joshbuddy/optitron#3]
this snippet

```
#!/usr/bin/env ruby -lrubygems

require 'optitron'

class CLI < Optitron::CLI
  desc "Say hello"
  def hello
    puts "hi"
  end

  protected

  def secret_method
    puts "ho"
  end
end

CLI.dispatch
```

interprets the following:

```
$ ./test.rb --help
Commands

hello               # Say hello
secret_method       # Say hello

Global options

-?/--help           # Print help message
```

**Comment by knoopx** [comment]
I'm not liking too much the new "api". Is optitron re-parsing source code using ruby_parser?

**Comment by joshbuddy** [comment]
Fixed in 0.1.7. It is using ruby_parser to parse the source code. You can avoid that parsing by using the non-class dsl. What would you prefer btw? I think we can kind of make it however we'd like. (And if there was a good solution that didn't involve parsing source, I'd like that.)

**Comment by joshbuddy** [comment]
I've added a dispatch method to response to allow dispatching to a target without resorting to ruby_parser. Take a look at the bottom of the README for an example of this. (This is in 0.1.8)

**Comment by knoopx** [comment]
nice, now we have flavors for all tastes :)
